version: "3"
services:
    postgres:
        container_name: "postgres"
        image: postgres
        volumes:
            - "pgdata:/var/lib/postgresql/data/"
        environment:
            POSTGRES_USER: ${TYPEORM_USERNAME}
            POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
            POSTGRES_DB: ${TYPEORM_DATABASE}
        ports:
            - "5432:5432"
    backend:
        container_name: "everypenny-api"
        image: node:16
        build: .
        command: "yarn start"
        ports:
            - "4000:4000"
        volumes:
            - .:/srv/backend
        # working_dir: /srv/backend
        depends_on:
            - postgres
        environment:
            DB_HOST: postgres

volumes:
    pgdata: {}